# Generated by Django 2.0.7 on 2020-08-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
