# Generated by Django 2.0.7 on 2020-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0002_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('MRP', models.IntegerField()),
                ('batchNum', models.IntegerField()),
                ('batchDate', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=10)),
            ],
        ),
    ]
